# NUMPY


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
arr = np.array(["alpha","beta","gemma"])
print(arr)
print(type(arr))

['alpha' 'beta' 'gemma']
<class 'numpy.ndarray'>


In [5]:
arr = np.array((1,2,3,4))
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
arr = np.array(43)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
43


In [ ]:
arr =np.array([[1,2,3,4]])
print(arr)

In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [19]:
arr = np.array([1,2,3])
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print (arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


In [21]:
arr = np.array([1,2,3,4] , ndmin =5)
print(arr)

[[[[[1 2 3 4]]]]]


In [22]:
arr = np.array([1,2,3,4])
print(arr[0])

1


In [23]:
arr = np.array([1,2,3,4,6,7,8])
print(arr[2]+arr[4])

9


In [6]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1])

6


In [ ]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0,1,2])
print(arr)

6
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [30]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:4])

[2 3 4]


In [31]:
arr = np.array([1,2,3,4,5])
print(arr[:3])

[1 2 3]


In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [9]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [11]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [13]:
arr = np.array(["hafsaaaa","areeha"])
print(arr.dtype)

<U8


In [14]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [16]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [ ]:
arr = np .arange(0,250) . reshape(5,5, 10)
print("3D matrixs")
print(arr)
middle_block = arr[2]
print("midle block element",middle_block)
element = arr[4,4,5]
print("Accessed Element",element)



3D matrixs
[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]]

 [[ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]]

 [[150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 22

In [2]:
import numpy as np
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[10,11,12,13],[14,15,16,17]])
print(arr1*arr2)

[[ 10  22  36  52]
 [ 70  90 112 136]]


In [15]:

arr1d = np.arange(16) 
print("1d array",arr1d)
arr2d = arr1d.reshape(1,16)
print ("2d array ",arr2d)
result = np.multiply(arr2d,arr1d)

print ("result", result)

1d array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
2d array  [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
result [[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]]
